#!/usr/bin/env bash

# Open the given filename in ZENLOG_VIEWER.

set -eou pipefail

file="$1"

if [[ -z "$file" ]]; then
    echo "zenlog open-viewer: Missing filename." 1>&2
    exit 1
fi

echo "zenlog: Opening $file ..."

viewer="${ZENLOG_VIEWER:-$PAGER}"
if [[ $viewer == "" ]] && command -v less >/dev/null 2>&1; then
    viewer="less"
fi

"$viewer" "$file"
